### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Lisennk** [ambiso/LiveEarth#2]
Linux Mint 17.3 Rosa
![image](https://cloud.githubusercontent.com/assets/8103985/14064560/4a7933c2-f410-11e5-9621-f0bb1314f39e.png)

**Comment by ambiso** [comment]
Please try

```
./bg.sh
```

**Comment by Lisennk** [comment]
./bg.sh: command not found

I do something wrong?

**Comment by ambiso** [comment]
Could you try changing the first line of the script from

```
#!/usr/bin/env bash
```

to

```
#!/bin/bash
```

then save and run again with

   ./bg.sh

**Comment by Lisennk** [comment]
Done, but:
`sudo: ./bg.sh: command not found`

**Comment by ambiso** [comment]
Cannot reproduce, nor find any related information.
