### ISSUE TITLE
bad final image

### ISSUE THREAD

**Issue by coffebar** [ambiso/LiveEarth#3]
final.png
![final](https://cloud.githubusercontent.com/assets/3100053/14761483/a72a29b2-096b-11e6-8b85-9df81475b6c7.png)

Output:

> I need feh to work
> Cleanup
> Download
> Failed to download images
> Check files
> Merge
> montage.im6: improper image header `/home/developer/.bg/0_1.png' @ error/png.c/ReadPNGImage/3675.
> montage.im6: improper image header`/home/developer/.bg/3_1.png' @ error/png.c/ReadPNGImage/3675.
> montage.im6: improper image header `/home/developer/.bg/2_2.png' @ error/png.c/ReadPNGImage/3675.
> montage.im6: improper image header`/home/developer/.bg/3_2.png' @ error/png.c/ReadPNGImage/3675.
> montage.im6: improper image header `/home/developer/.bg/1_3.png' @ error/png.c/ReadPNGImage/3675.
> montage.im6: improper image header`/home/developer/.bg/2_3.png' @ error/png.c/ReadPNGImage/3675.
> Cleanup
> Set background

**Comment by coffebar** [comment]
some problems with image downloading, successfully after the fifth time

**Comment by ambiso** [comment]
If the problem comes up again, try increasing the delay variable to say 240.
Also, you probably modified the script, or why is it not exiting upon printing 'I need feh to work'?

**Comment by coffebar** [comment]
I have commented only last line.

> why is it not exiting upon printing 'I need feh to work'?

Don't know)

when call script like that
`. bg.sh && gedit`
it continues even after message 'I need feh to work'
